### ISSUE TITLE
Open source the repo

### ISSUE THREAD

**Issue by remy** [eHealthAfrica/universal-exporter#1]
- [x] Ready

Reviewers:
- [x] @rmehner 
- [x] @danse (is the kid below...ssssh don't tell anyone)

![tumblr_nfx7orzfvs1qzsowjo1_400](https://cloud.githubusercontent.com/assets/13700/8700121/fd5894c0-2b01-11e5-9323-a7bade75f30d.gif)

**Comment by danse** [comment]
i totally want to be that kid, i am on this!

**Comment by danse** [comment]
files in here are really long https://github.com/eHealthAfrica/universal-exporter/tree/master/examples/remote-server/public. they are built out of something else i hope

**Comment by danse** [comment]
those files are a copy of dist files. for the rest, i went through the code and there is no sensitive info, so :+1: for open sourcing!

:sunglasses:

**Comment by rmehner** [comment]
Looks good to me :+1: 

Good work!

**Comment by danse** [comment]
:tada:

**Comment by tthew** [comment]
:remy:
